-- AlterTable
ALTER TABLE "Postcard"
ADD COLUMN "likeCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "dislikeCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "wrongLocationReports" INTEGER NOT NULL DEFAULT 0;
